### ISSUE TITLE
Model attributes with `nullable: true` property not rendering type null

### ISSUE THREAD

**Issue by jschaefer77** [stoplightio/elements#2136]
Some of our models have attribute types like string and in addition null.

## Current Behavior
In Stoplight Studio type string and null is rendered in preview mode, 
![image](https://user-images.githubusercontent.com/52877209/165688997-3b444bc2-c42c-426a-a883-9ff68ee74f5d.png)

But not in standalone version of elements. Only type string is shown.
![image](https://user-images.githubusercontent.com/52877209/165688824-0b983afe-e8a8-48c0-8e86-84033070cb0d.png)

## Expected Behavior
Both types (e.g. string and null) should be rendered.

## Possible Workaround/Solution
No workaround possible

## Steps to Reproduce
1. Create a model with one attribute. Attribute type set to string and null.
2. Check how the attribute is rendered in elements.
3. 
4.
5.

## Environment

- Version used: 7.5.15
- Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome and Firefox
- Operating System and version (desktop or mobile):
- Link to your environment/workspace/project:

**Comment by falsaffa** [comment]
@jschaefer77 It looks like this issue is resolved as of the latest version of Elements. I created a model with types `string` or `null` and the types are being rendered correctly. I'll leave this issue open for a few days for you to confirm.

![Screenshot 2023-07-06 at 9 12 01 AM](https://github.com/stoplightio/elements/assets/44938179/f8b611b0-2bbd-416a-b4c3-a8e08d96efde)

**Comment by jschaefer77** [comment]
Hey @falsaffa , to which version of Elements did o you refer? I tested again with 7.7.18 and the issue still occours.

**Comment by jschaefer77** [comment]
I have to use OpenAPI 3.0, that's why I use nullable. I can't switch to OpenAPI 3.1 because of the bad tool support for Golang.
But I can at least confirm that it works with OpenAPI3.1, but not for OpenAPI 3.0

**Comment by falsaffa** [comment]
@jschaefer77 Thanks for confirming. I updated the title to highlight the issue on the schema level.

I can't commit to a timeline, but if you would like to open a PR with the fix I'll be happy to review it.

**Comment by jschaefer77** [comment]
@falsaffa , unfortunately I am not a web dev.

**Comment by kaylachun** [comment]
@jschaefer77 This should be working as expected now.  If `nullable` is set to true the `null` type will be appended.
